In [40]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
df = pd.read_csv('flipkart_com-ecommerce_sample.csv')

In [42]:
df.head()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  str
 1   crawl_timestamp          20000 non-null  str
 2   product_url              20000 non-null  str
 3   product_name             20000 non-null  str
 4   product_category_tree    20000 non-null  str
 5   pid                      20000 non-null  str
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  str
 9   is_FK_Advantage_product  20000 non-null  bool
 10  description              19998 non-null  str
 11  product_rating           20000 non-null  str
 12  overall_rating           20000 non-null  str
 13  brand                    14136 non-null  str
 14  product_specifications   19986 non-null  str
dtypes: bool(1), float64(2), str(12)
memory usage: 2.2 MB

In [44]:
df['product_rating'].unique()

<StringArray>
['No rating available',                   '5',                   '3',
                 '3.6',                 '3.5',                 '4.4',
                   '4',                   '1',                 '2.3',
                 '4.8',                 '2.7',                 '4.5',
                 '2.4',                 '3.2',                 '4.7',
                   '2',                 '3.3',                 '4.3',
                 '3.8',                 '4.2',                 '3.7',
                 '3.9',                 '2.5',                 '3.1',
                 '4.1',                 '3.4',                 '4.6',
                 '1.5',                 '2.8',                 '2.9',
                 '4.9',                 '2.2',                 '2.6',
                 '1.3',                 '1.7',                 '1.8']
Length: 36, dtype: str

In [45]:
df['overall_rating'].unique()

<StringArray>
['No rating available',                   '5',                   '3',
                 '3.6',                 '3.5',                 '4.4',
                   '4',                   '1',                 '2.3',
                 '4.8',                 '2.7',                 '4.5',
                 '2.4',                 '3.2',                 '4.7',
                   '2',                 '3.3',                 '4.3',
                 '3.8',                 '4.2',                 '3.7',
                 '3.9',                 '2.5',                 '3.1',
                 '4.1',                 '3.4',                 '4.6',
                 '1.5',                 '2.8',                 '2.9',
                 '4.9',                 '2.2',                 '2.6',
                 '1.3',                 '1.7',                 '1.8']
Length: 36, dtype: str

## Cleanup

In [46]:
"""
1 - Drop duplicate values using pid
2 - Both product rating and overall rating column are same we delete one 
3 - we dont need product url and image so we dropp'em
4 - expanding product category tree and putting it in df
5 - changing data type of crawl_date to date
6 - Product rating name change and data type change



"""

"\n1 - Drop duplicate values using pid\n2 - Both product rating and overall rating column are same we delete one \n3 - we dont need product url and image so we dropp'em\n4 - expanding product category tree and putting it in df\n5 - changing data type of crawl_date to date\n6 - Product rating name change and data type change\n\n\n\n"

#### Dropping duplicates

In [47]:
df.drop_duplicates(subset='pid', inplace = True)
df.reset_index(drop=True, inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19998 entries, 0 to 19997
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  19998 non-null  str
 1   crawl_timestamp          19998 non-null  str
 2   product_url              19998 non-null  str
 3   product_name             19998 non-null  str
 4   product_category_tree    19998 non-null  str
 5   pid                      19998 non-null  str
 6   retail_price             19920 non-null  float64
 7   discounted_price         19920 non-null  float64
 8   image                    19995 non-null  str
 9   is_FK_Advantage_product  19998 non-null  bool
 10  description              19996 non-null  str
 11  product_rating           19998 non-null  str
 12  overall_rating           19998 non-null  str
 13  brand                    14134 non-null  str
 14  product_specifications   19984 non-null  str
dtypes: bool(1), float64(2), str(12)
memory usage: 2.2 MB

#### Dropping image and overall rating

In [48]:
df.drop(columns = ['image', 'overall_rating', 'product_url','uniq_id'], inplace = True)

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19998 entries, 0 to 19997
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   crawl_timestamp          19998 non-null  str
 1   product_name             19998 non-null  str
 2   product_category_tree    19998 non-null  str
 3   pid                      19998 non-null  str
 4   retail_price             19920 non-null  float64
 5   discounted_price         19920 non-null  float64
 6   is_FK_Advantage_product  19998 non-null  bool
 7   description              19996 non-null  str
 8   product_rating           19998 non-null  str
 9   brand                    14134 non-null  str
 10  product_specifications   19984 non-null  str
dtypes: bool(1), float64(2), str(8)
memory usage: 1.5 MB

#### Individual Category

In [50]:
df['product_category_tree'].unique()
df['product_category_tree'] =  df['product_category_tree'].str.replace('["', '').str.replace('"]','')
categories = df['product_category_tree'].str.split(' >> ', expand=True)
categories

df['main_category'] = categories[0]
df['sub_category'] = categories[1]

df[['product_name','main_category','sub_category']].head(10)

,product_name,main_category,sub_category
0,Alisha Solid Women's Cycling Shorts,Clothing,Women's Clothing
1,FabHomeDecor Fabric Double Sofa Bed,Furniture,Living Room Furniture
2,AW Bellies,Footwear,Women's Footwear
3,Alisha Solid Women's Cycling Shorts,Clothing,Women's Clothing
4,Sicons All Purpose Arnica Dog Shampoo,Pet Supplies,Grooming
5,Eternal Gandhi Super Series Crystal Paper Weig...,Eternal Gandhi Super Series Crystal Paper Weig...,NaN
6,Alisha Solid Women's Cycling Shorts,Clothing,Women's Clothing
7,FabHomeDecor Fabric Double Sofa Bed,Furniture,Living Room Furniture
8,"dilli bazaaar Bellies, Corporate Casuals, Casuals",Footwear,Women's Footwear
9,Alisha Solid Women's Cycling Shorts,Clothing,Women's Clothing

#### product rating name change to rating and datatype change

In [51]:

df.rename(columns={'product_rating':'Rating'}, inplace=True)
df['Rating'] = df['Rating'].replace('No rating available', np.nan)
df['Rating'] = df['Rating'].astype(float)
df['Rating'].unique()

array([nan, 5. , 3. , 3.6, 3.5, 4.4, 4. , 1. , 2.3, 4.8, 2.7, 4.5, 2.4,
       3.2, 4.7, 2. , 3.3, 4.3, 3.8, 4.2, 3.7, 3.9, 2.5, 3.1, 4.1, 3.4,
       4.6, 1.5, 2.8, 2.9, 4.9, 2.2, 2.6, 1.3, 1.7, 1.8])

#### Date Fix

In [52]:
df.rename(columns={'crawl_timestamp': 'date'}, inplace=True)
df['date'] = pd.to_datetime(df['date'])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19998 entries, 0 to 19997
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     19998 non-null  datetime64[us, UTC]
 1   product_name             19998 non-null  str
 2   product_category_tree    19998 non-null  str
 3   pid                      19998 non-null  str
 4   retail_price             19920 non-null  float64
 5   discounted_price         19920 non-null  float64
 6   is_FK_Advantage_product  19998 non-null  bool
 7   description              19996 non-null  str
 8   Rating                   1849 non-null   float64
 9   brand                    14134 non-null  str
 10  product_specifications   19984 non-null  str
 11  main_category            19998 non-null  str
 12  sub_category             19670 non-null  str
dtypes: bool(1), datetime64[us, UTC](1), float64(3), str(8)
memory usage: 1.9 MB

#### Both price columns checking

In [53]:
df['retail_price'].isnull().sum()
df['discounted_price'].isnull().sum()

# Both are 78 so ig both are null at same index

# Dropping those rows where value is null

df.dropna(subset='retail_price', inplace=True)
df['retail_price'].isnull().sum()
df['discounted_price'].isnull().sum()


# so its doneeeeeeeeeeeeeeee

np.int64(0)

In [54]:
df.head()

,date,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,description,Rating,brand,product_specifications,main_category,sub_category
0,2016-03-25 22:59:23+00:00,Alisha Solid Women's Cycling Shorts,"Clothing >> Women's Clothing >> Lingerie, Slee...",SRTEH2FF9KEDEFGF,999.0,379.0,False,Key Features of Alisha Solid Women's Cycling S...,NaN,Alisha,"{""product_specification""=>[{""key""=>""Number of ...",Clothing,Women's Clothing
1,2016-03-25 22:59:23+00:00,FabHomeDecor Fabric Double Sofa Bed,Furniture >> Living Room Furniture >> Sofa Bed...,SBEEH3QGU7MFYJFY,32157.0,22646.0,False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,NaN,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati...",Furniture,Living Room Furniture
2,2016-03-25 22:59:23+00:00,AW Bellies,Footwear >> Women's Footwear >> Ballerinas >> ...,SHOEH4GRSUBJGZXE,999.0,499.0,False,Key Features of AW Bellies Sandals Wedges Heel...,NaN,AW,"{""product_specification""=>[{""key""=>""Ideal For""...",Footwear,Women's Footwear
3,2016-03-25 22:59:23+00:00,Alisha Solid Women's Cycling Shorts,"Clothing >> Women's Clothing >> Lingerie, Slee...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,Key Features of Alisha Solid Women's Cycling S...,NaN,Alisha,"{""product_specification""=>[{""key""=>""Number of ...",Clothing,Women's Clothing
4,2016-03-25 22:59:23+00:00,Sicons All Purpose Arnica Dog Shampoo,Pet Supplies >> Grooming >> Skin & Coat Care >...,PSOEH3ZYDMSYARJ5,220.0,210.0,False,Specifications of Sicons All Purpose Arnica Do...,NaN,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",...",Pet Supplies,Grooming

**Data is clean now, so lets work on our KPIs**

## KPIs

In [55]:
"""
IMP KPIs that we can find

1 - Top ten categories
2 - Which Brand generates most avg money 
3 - We can check monthly sales here and which category and brand is at top every month in avg sales 
4 - We can split the category column to check which category hast most sales.
5 - is_fk_advantage = flipkart advantage or now flipkart assured where the product goes through strict checking and all
    i) We can use it to check wheather fk products have more rating or not
    ii) Do these products have more price or more discount
    iii) Which category has most fk_advantage

"""

'\nIMP KPIs that we can find\n\n1 - Top ten categories\n2 - Which Brand generates most avg money \n3 - We can check monthly sales here and which category and brand is at top every month in avg sales \n4 - We can split the category column to check which category hast most sales.\n5 - is_fk_advantage = flipkart advantage or now flipkart assured where the product goes through strict checking and all\n    i) We can use it to check wheather fk products have more rating or not\n    ii) Do these products have more price or more discount\n    iii) Which category has most fk_advantage\n\n'

In [61]:
# Top ten categories 

df.groupby('main_category')['discounted_price'].sum().sort_values(ascending=False).head(10).reset_index()


# Couting total products in each category
# df.groupby('main_category')['pid'].count().reset_index().sort_values(by = 'pid',ascending=False).head(10)

                main_category  discounted_price
0                   Jewellery        19578167.0
1                    Clothing         4407230.0
2                   Furniture         3080605.0
3  Home Decor & Festive Needs         1701745.0
4                     Watches         1355850.0
5                    Footwear         1319710.0
6                  Automotive         1201041.0
7                   Computers         1192585.0
8       Mobiles & Accessories         1050231.0
9             Home Furnishing          863972.0

In [71]:
# Which Brand generates most avg money and thier quantity

df.groupby(['brand','main_category']).agg(
    revenue = ('discounted_price','mean'),
    quantity =  ('pid','count')
).sort_values(by = 'revenue' ,ascending=False).head(10).reset_index()

# Count
# df.groupby('brand')['pid'].count().reset_index().sort_values(by = 'pid',ascending=False).head(10)

              brand          main_category        revenue  quantity
0            Audeze  Mobiles & Accessories  116292.000000         1
1            Durian              Furniture   47745.967742        31
2              Reet              Jewellery   41499.000000         1
3      Theme Jewels              Jewellery   40818.000000         1
4  Suranas Jewelove              Jewellery   40000.000000         1
5            Ratnam              Jewellery   39775.000000         4
6              ARRA              Furniture   37426.807692        26
7         WhiteGems              Jewellery   35319.333333         3
8     Sakshi Jewels              Jewellery   35180.000000         1
9             Jisha              Jewellery   35067.000000         3

In [72]:
# With those which have higher quantity (quantity > 10)
df.groupby(['brand','main_category']).agg(
    revenue = ('discounted_price','mean'),
    quantity =  ('pid','count')
).query('quantity >= 10').sort_values(by = 'revenue' ,ascending=False).head(10).reset_index()

             brand main_category       revenue  quantity
0           Durian     Furniture  47745.967742        31
1             ARRA     Furniture  37426.807692        26
2            Rakam     Jewellery  30964.400000        25
3   Fullcutdiamond     Jewellery  30694.863636        22
4  Shashvat Jewels     Jewellery  30243.722222        18
5   Diti Jewellery     Jewellery  28834.615385        13
6        BlueStone     Jewellery  28249.585859        99
7          Jewels5     Jewellery  27451.653846        26
8      Radiant Bay     Jewellery  27287.462121       132
9       Karatcraft     Jewellery  26696.199052       211

In [95]:
# Monthly sales and which category and brand is at top every month in avg sale
# lets add a year month column in our df

df['year_month'] = df['date'].dt.strftime('%Y-%m')

df.groupby('year_month')['discounted_price'].sum().reset_index().sort_values(by = 'year_month').head(10)

  year_month  discounted_price
0    2015-12        12009320.0
1    2016-01        21498650.0
2    2016-02          264539.0
3    2016-03         2507724.0
4    2016-04         1391281.0
5    2016-05          703063.0
6    2016-06          936635.0

In [107]:
"""
To get the monthly sale and the brand on top we have to create two tables one is monthly
sales and top category sales then we merge these two
"""

monthly_sales = df.groupby('year_month')['discounted_price'].sum().reset_index().sort_values(by = 'year_month').head(10).rename(columns={'discounted_price':'Total Revenue'})

# Top category per month
top_cat = df.groupby(['year_month','main_category'])['discounted_price'].sum().reset_index().sort_values(['year_month','discounted_price'], ascending=[True, False]).groupby('year_month').first().reset_index().rename(columns={"main_category":"Top Category", "discounted_price": "Category Revenue"})

Top_cat_month = pd.merge(monthly_sales, top_cat, on='year_month')
Top_cat_month

  year_month  Total Revenue Top Category  Category Revenue
0    2015-12     12009320.0    Furniture         2592373.0
1    2016-01     21498650.0    Jewellery        17810412.0
2    2016-02       264539.0   Automotive           55419.0
3    2016-03      2507724.0     Clothing          465097.0
4    2016-04      1391281.0     Clothing          400564.0
5    2016-05       703063.0     Clothing          214006.0
6    2016-06       936635.0     Clothing          297674.0

In [ ]:
# Flipkart Advantage or assured
"""
    i) We can use it to check wheather fk products have more rating or not
    ii) Do these products have more price or more discount
    iii) Which category has most fk_advantage
"""

df['is_FK_Advantage_product'].value_counts()

is_FK_Advantage_product
False    19152
True       768
Name: count, dtype: int64

In [117]:
# i) We can use it to check wheather fk products have more rating or not

df.groupby('is_FK_Advantage_product')['Rating'].mean().reset_index()

   is_FK_Advantage_product    Rating
0                    False  3.814351
1                     True  3.790196

In [129]:
# ii) Do these products have more price or more discount

# lets create a column discount percentage
df['dis_per'] = (((df['retail_price'] - df['discounted_price'])/df['retail_price'])*100).round(2)
df['dis_per']

df.groupby('is_FK_Advantage_product').agg(
    avg_price = ('retail_price','mean'),
    avg_discount_percent =  ('dis_per','mean')
).reset_index()

   is_FK_Advantage_product    avg_price  avg_discount_percent
0                    False  3027.636278             41.024013
1                     True  1774.161458             28.093385

In [132]:
# iii) Which category has most fk_advantage

df.groupby('main_category')['is_FK_Advantage_product'].sum().sort_values(ascending=False).head(10).reset_index()

            main_category  is_FK_Advantage_product
0                Clothing                      338
1                 Watches                      158
2                Footwear                       81
3               Computers                       49
4        Tools & Hardware                       25
5               Jewellery                       16
6                  eBooks                       15
7        Sports & Fitness                       13
8  Toys & School Supplies                       11
9   Mobiles & Accessories                        9

In [133]:
df.to_csv("Flipkart_cleaned_data.csv", index=False)